image: Ubuntu2004  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки

test_script:
  - yarn run lint && yarn run test  # скрипт тестирования

